ALTER TABLE tasks ADD COLUMN retry_count INT NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN max_retries INT NOT NULL DEFAULT 3;
ALTER TABLE tasks ADD COLUMN next_attempt_at TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN dead_letter_at TIMESTAMPTZ;